### ISSUE TITLE
ЛР 1 makefile

### ISSUE THREAD

**Issue by alexandr-kaa** [nbphleb/SRV#1]
Прошу проверить makefile. По размеру исполняемых файлов непохоже, чтобы добавилась отладочная информация и кроме того, нет отдельных исполняемых файлов для отладочной версии. Debug затирают release?

**Comment by alexandr-kaa** [comment]
![изображение](https://user-images.githubusercontent.com/63350411/235346352-22e585ce-7de1-4fa1-98bf-2b76913ad900.png)

**Comment by nbphleb** [comment]
@alexandr-kaa Здравствуйте. Исправила makefile. Также добавила другие лабораторные

**Comment by alexandr-kaa** [comment]
После исправления не выводится ФИО, debug сборка затирает релиз, нужно исправить makefile
